#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Mon Feb 14 19:54:52 IST 2022
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 31629cb043a147f3a8dd2d1eb0b654fd --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot tb_kernel3x3_behav xil_defaultlib.tb_kernel3x3 -log elaborate.log"
xelab -wto 31629cb043a147f3a8dd2d1eb0b654fd --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot tb_kernel3x3_behav xil_defaultlib.tb_kernel3x3 -log elaborate.log

