#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Mon Feb 14 19:54:54 IST 2022
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim tb_kernel3x3_behav -key {Behavioral:sim_1:Functional:tb_kernel3x3} -tclbatch tb_kernel3x3.tcl -view /home/htic-broncho/DLHW/Vivado/conv2d/tb_kernel3x3_behav.wcfg -log simulate.log"
xsim tb_kernel3x3_behav -key {Behavioral:sim_1:Functional:tb_kernel3x3} -tclbatch tb_kernel3x3.tcl -view /home/htic-broncho/DLHW/Vivado/conv2d/tb_kernel3x3_behav.wcfg -log simulate.log

